name: AI Review

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - name: prebuild
        run: pnpm install --frozen-lockfile

      - name: Build
        run: cd packages/ai-craftsman && pnpm build

      - name: AI Review
        run: node packages/ai-craftsman/dist/bin.js
        env:
          BASE_REF: ${{ github.base_ref }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          LANGUAGE: Japanese
          CODING_GUIDE_PATH: ExampleOfCodigRules.md
          # CODING_GUIDE_READER: packages/ai-craftsman/dist/ci/codingGuide.js
          DEBUG: true
